use unique solr service name. #454
Sitecore/Sitecore-Instance-Manager pull request #463
Opened 2020-09-24 15:20 UTC by IvanSheyenko

2020-09-24 18:45 UTC, AndreyFilchenkov requested changes

2020-09-24 18:45 UTC, AndreyFilchenkov commented on src/SIM.Tool/CustomSifConfig/Solr/Solr-SingleDeveloper.json
> -    "SolrServicePrefix": {
We need to reflect changes in the 'AddSolrToSimConfig' type.

2020-10-06 17:58 UTC, ViacheslavAfanasyev approved these changes

2020-10-07 18:59 UTC, IvanSheyenko commented on src/SIM.Tool/CustomSifConfig/Solr/Solr-SingleDeveloper.json
> -    "SolrServicePrefix": {
done

2020-10-12 20:05 UTC, AndreyFilchenkov approved these changes

2020-10-12 20:06 UTC, merged