Feature/changes to build sxa sites
Sitecore/Sitecore-Instance-Manager pull request #465
Opened 2020-09-29 09:08 UTC by navancommits

Supports SXA based websites for 9.3 and 10 versions since this is necessary for building Commerce-based sites

2020-09-29 13:56 UTC, IvanSheyenko commented
@navancommits The link to the blog post leads to 404. Could you please provide a working one or describe the changes in details here?

2020-09-29 17:12 UTC, navancommits commented
Sure Ivan,  thanks for responding, here it is -
http://navansitecorenotes.blogspot.com/2020/09/sitecore-instance-manager-sim-support_29.html



On Tue, 29 Sep. 2020, 11:56 pm Ivan Sheyenko, <notifications@github.com>
wrote:

> @navancommits <https://github.com/navancommits> The link to the blog post
> leads to 404. Could you please provide a working one or describe the
> changes in details here?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Sitecore/Sitecore-Instance-Manager/pull/465#issuecomment-700721816>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANDXDKWRNFUHFX5FNWAXITLSIHRRVANCNFSM4R5QYSNQ>
> .
>

2020-09-29 18:10 UTC, IvanSheyenko requested changes

2020-09-29 18:10 UTC, IvanSheyenko commented on src/SIM.Tool/GlobalParamsConfig/XP/GlobalParams_9.2_Setup_XP0.json
> +﻿{
what is the purpose of this file? It is an exact copy of the 9.2.0 global params file

2020-09-29 18:10 UTC, IvanSheyenko commented on src/SIM.Tool/GlobalParamsConfig/XP/GlobalParams_9.3_Setup_XP0.json
> +				"SiteName": "$SqlDbPrefix+\".local\""
SXA-Solr task does not have SiteName parameter. Please remove.

2020-09-29 18:10 UTC, IvanSheyenko commented on src/SIM.Tool/SIM.Tool.csproj
> +    <None Include="GlobalParamsConfig\XP\GlobalParams_10.0_Setup_XP0.json" />
Set copy always copy to output dir. Currently file is not copied to the build dir.

2020-09-29 19:23 UTC, IvanSheyenko requested changes
Also please consider renaming your global params files as setup suffix is not informative. May be something like GlobalParams_10.0_XP0_SXA.json

2020-09-30 06:13 UTC, AndreyFilchenkov requested changes

2020-09-30 06:13 UTC, AndreyFilchenkov commented on src/SIM.Products/Product.cs
> +                  Revision = revision.Replace(".zip", " with SXA")
The 'Product.cs' class is used for different Sitecore/Modules packages. So we should not add the "SXA" value to the revision.
Please consider leaving the 'Revision = revision' code unchanged.

2020-09-30 06:13 UTC, AndreyFilchenkov commented on src/SIM.Products/Product.cs
> +    private const string ProductRevisionPattern = @"(\d\d\d\d\d\d([\d\w\s_\-\!\(\)]*|[\d\w\s_\-.\!\(\)]+\.[\d\w\s_\-.\!\(\)]+))"; // @"(\d\d\d\d\d\d)";//the additional \.\ after \-\ will allow the do
Please consider using the following pattern to get the ```revision``` value without the trailing ```.zip```:
```c#
private const string ProductRevisionPattern = @"(\d\d\d\d\d\d([\d\w\s_\-\!\(\)]*|[\d\w\s_\-\!\(\)]+\.[\d\w\s_\-\.\!]+\)))";
```

2020-09-30 07:07 UTC, navancommits commented on src/SIM.Products/Product.cs
> +                  Revision = revision.Replace(".zip", " with SXA")
instead of SXA, further down, is it ok if i check for "Developer Workstation" instead of "SXA" in the display name? If you let me know, will add the same and push the work....

2020-10-03 11:11 UTC, AndreyFilchenkov commented on src/SIM.Products/Product.cs
> +                  Revision = revision.Replace(".zip", " with SXA")
Yes, it is, you can check for "Developer Workstation" in the display name.

2020-10-03 12:35 UTC, navancommits commented
I already made the changes based on the review comments and pushed the code
couple of days back... please let me know if you have any questions...

On Sat, 3 Oct. 2020, 9:11 pm Andrey Filchenkov, <notifications@github.com>
wrote:

> *@AndreyFilchenkov* commented on this pull request.
> ------------------------------
>
> In src/SIM.Products/Product.cs
> <https://github.com/Sitecore/Sitecore-Instance-Manager/pull/465#discussion_r499138921>
> :
>
> > @@ -635,7 +635,7 @@ private static bool TryParse([NotNull] string packagePath, [NotNull] Match match
>                    PackagePath = packagePath,
>                    TwoVersion = $"{arr[0]}.{arr[1]}",
>                    TriVersion = version,
> -                  Revision = revision
> +                  Revision = revision.Replace(".zip", " with SXA")
>
> Yes, it is, you can check for "Developer Workstation" in the display name.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Sitecore/Sitecore-Instance-Manager/pull/465#discussion_r499138921>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANDXDKSRD6ICWMXXN75CZXLSI4BHRANCNFSM4R5QYSNQ>
> .
>

2020-10-06 14:14 UTC, IvanSheyenko commented on src/SIM.Tool/GlobalParamsConfig/GlobalSettings.json
> -  "GlobalFilesMap": {
@navancommits as I can see spacing in globalsettings.json file is not fixed yet

2020-10-07 19:06 UTC, IvanSheyenko commented on src/SIM.Tool/GlobalParamsConfig/GlobalSettings.json
> -  "GlobalFilesMap": {
@navancommits https://www.screencast.com/t/qPnw48YAinzb

2020-10-07 20:59 UTC, navancommits reviewed
@IvanSheyenko , hope its covered now....

2020-10-12 20:08 UTC, AndreyFilchenkov approved these changes

2020-10-27 15:08 UTC, IvanSheyenko approved these changes

2020-10-27 19:40 UTC, merged