449 Add observable collection and change logic of adding a new instance
Sitecore/Sitecore-Instance-Manager pull request #468
Opened 2020-10-06 20:28 UTC by ViacheslavAfanasyev

2020-10-07 19:42 UTC, IvanSheyenko requested changes

2020-10-07 19:42 UTC, IvanSheyenko commented on src/SIM.Adapters/WebServer/Website.cs
> +    private string name { get; set; }
Make it a field, not property. No sense in private property

2020-10-07 19:42 UTC, IvanSheyenko commented on src/SIM.Instances/Instance.cs
> +      _SitecoreEnvironment = SitecoreEnvironmentHelper.GetExistingOrNewSitecoreEnvironment(this.Name);
This creates a new environment if one does not exist. Looks like this will create environments for sitecore 8 which is not desirable.

2020-10-07 19:42 UTC, IvanSheyenko commented on src/SIM.Instances/Instance.cs
> +          _SitecoreEnvironment = SitecoreEnvironmentHelper.GetExistingOrNewSitecoreEnvironment(this.Name);
if it is set in constructor why do we need to resolve it here?

2020-10-07 19:42 UTC, IvanSheyenko commented on src/SIM.Instances/InstanceManager.cs
> +    public RangeObservableCollection<Instance> InstancesObservableCollection;
should be a property. No public fields pls.

2020-10-07 19:42 UTC, IvanSheyenko commented on src/SIM.Instances/InstanceManager.cs
> +        var instance = new Instance((int)id);
what if instance with the given ID does not exist?

2020-10-07 19:42 UTC, IvanSheyenko commented on src/SIM.Instances/InstanceManager.cs
> +              Site site = sites.FirstOrDefault(s => s.Name == member.Name);
need to check that a member is of a site type.

2020-10-07 19:42 UTC, IvanSheyenko commented on src/SIM.Instances/InstanceManager.cs
> +          this.Instances = this.Instances.Add(instance);
what is the purpose of reassigning instances?

2020-10-07 19:42 UTC, IvanSheyenko commented on src/SIM.Instances/InstanceManager.cs
> -    public Instance GetInstance(long id)
is this the same method as added above?

2020-10-07 19:42 UTC, IvanSheyenko commented on src/SIM.Tool.Windows/MainWindowHelper.cs
> +            }
what are these changes? remove and add the same code or am I missing something?

2020-10-08 17:32 UTC, ViacheslavAfanasyev commented on src/SIM.Adapters/WebServer/Website.cs
> +    private string name { get; set; }
Done

2020-10-08 17:32 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/Instance.cs
> +      _SitecoreEnvironment = SitecoreEnvironmentHelper.GetExistingOrNewSitecoreEnvironment(this.Name);
Please, see how it works earlier. I've introduced only the cache layer.

2020-10-08 17:32 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/Instance.cs
> +          _SitecoreEnvironment = SitecoreEnvironmentHelper.GetExistingOrNewSitecoreEnvironment(this.Name);
public virtual SitecoreEnvironment SitecoreEnvironment
{
	get { return SitecoreEnvironmentHelper.GetExistingOrNewSitecoreEnvironment(this.Name); }
}

2020-10-08 17:33 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/Instance.cs
> +      _SitecoreEnvironment = SitecoreEnvironmentHelper.GetExistingOrNewSitecoreEnvironment(this.Name);
public virtual SitecoreEnvironment SitecoreEnvironment
{
get { return SitecoreEnvironmentHelper.GetExistingOrNewSitecoreEnvironment(this.Name); }
}

2020-10-08 17:33 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/Instance.cs
> +          _SitecoreEnvironment = SitecoreEnvironmentHelper.GetExistingOrNewSitecoreEnvironment(this.Name);
It's the realization of the property, in case _SitecoreEnvironment field is null, the property guarantees that it returns the value.
I've added it to the constructor in order to initialize it when the object is created.

2020-10-08 17:33 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/InstanceManager.cs
> +    public RangeObservableCollection<Instance> InstancesObservableCollection;
This should be a property and it's updated from out of this class.

2020-10-08 17:34 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/InstanceManager.cs
> +        var instance = new Instance((int)id);
It isn't my code if you are talking about GetInstance method.

2020-10-08 17:34 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/InstanceManager.cs
> +              Site site = sites.FirstOrDefault(s => s.Name == member.Name);
Done

2020-10-08 17:34 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/InstanceManager.cs
> +          this.Instances = this.Instances.Add(instance);
The add method doesn't update the collection itself, it returns a new one. I need to update it.

2020-10-08 17:35 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/InstanceManager.cs
> -    public Instance GetInstance(long id)
Didn't get what you've meant

2020-10-08 17:35 UTC, ViacheslavAfanasyev commented on src/SIM.Tool.Windows/MainWindowHelper.cs
> +            }
It seems no changes, VS did it itself :-)

2020-10-12 21:03 UTC, AndreyFilchenkov requested changes

2020-10-12 21:03 UTC, AndreyFilchenkov commented on src/SIM.Adapters/WebServer/Website.cs
> +          Log.Error(ex.Message+" "+ex.StackTrace);
Please use the 'Log.Error(exception, message)'. It takes the 'exception' as the first argument.

2020-10-23 18:01 UTC, IvanSheyenko commented on src/SIM.Instances/Instance.cs
> +          _SitecoreEnvironment = SitecoreEnvironmentHelper.GetExistingOrNewSitecoreEnvironment(this.Name);
if it is set in constructor it is never null in property.

2020-10-23 18:03 UTC, IvanSheyenko commented on src/SIM.Instances/InstanceManager.cs
> +        var instance = new Instance((int)id);
then why is it marked as added in the PR?

2020-10-23 18:05 UTC, IvanSheyenko commented on src/SIM.Instances/InstanceManager.cs
> -    public Instance GetInstance(long id)
on line 177 the same method is added and removed here.

2020-10-23 18:06 UTC, IvanSheyenko commented on src/SIM.Tool.Windows/MainWindowHelper.cs
> +            }
control your VS pls :)

2020-11-04 17:06 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/Instance.cs
> +          _SitecoreEnvironment = SitecoreEnvironmentHelper.GetExistingOrNewSitecoreEnvironment(this.Name);
Yes, but if something went wrong and _SitecoreEnvironment == null, we need a mechanism which will initialize _SitecoreEnvironment property

2020-11-04 17:18 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/InstanceManager.cs
> +        var instance = new Instance((int)id);
It seems VS formated it somehow. There are also removes of these lines in the commit.
https://www.screencast.com/t/2JXv5dLUe

2020-11-04 17:18 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/InstanceManager.cs
> -    public Instance GetInstance(long id)
177 line doesn't have changes
https://www.screencast.com/t/fasrHTZzT

2020-11-04 17:23 UTC, ViacheslavAfanasyev commented on src/SIM.Adapters/WebServer/Website.cs
> +          Log.Error(ex.Message+" "+ex.StackTrace);
Done

2020-11-04 17:24 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/InstanceManager.cs
> +    public RangeObservableCollection<Instance> InstancesObservableCollection;
Done

2020-11-08 22:21 UTC, AndreyFilchenkov approved these changes

2020-11-18 15:41 UTC, IvanSheyenko commented on src/SIM.Instances/Instance.cs
> +          _SitecoreEnvironment = SitecoreEnvironmentHelper.GetExistingOrNewSitecoreEnvironment(this.Name);
If something goes wrong exception should be thrown

2020-11-18 16:00 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/Instance.cs
> +          _SitecoreEnvironment = SitecoreEnvironmentHelper.GetExistingOrNewSitecoreEnvironment(this.Name);
It's a realization of property and it doesn't care when and where it was initialized. So, if you have a better idea, let me know.

2020-11-25 14:24 UTC, IvanSheyenko commented on src/SIM.Instances/Instance.cs
> +          _SitecoreEnvironment = SitecoreEnvironmentHelper.GetExistingOrNewSitecoreEnvironment(this.Name);
Initialize it in a constructor or in property, not both

2020-11-25 14:38 UTC, IvanSheyenko commented on src/SIM.Instances/InstanceManager.cs
> +    public RangeObservableCollection<Instance> InstancesObservableCollection;
It is still a field pls use property.

2020-11-25 15:34 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/InstanceManager.cs
> +    public RangeObservableCollection<Instance> InstancesObservableCollection;
Done

2020-11-25 15:34 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/Instance.cs
> +          _SitecoreEnvironment = SitecoreEnvironmentHelper.GetExistingOrNewSitecoreEnvironment(this.Name);
Done

2020-12-01 15:09 UTC, IvanSheyenko approved these changes

2020-12-09 15:51 UTC, merged