Feature/299 refactor the code related to buttons
Sitecore/Sitecore-Instance-Manager pull request #469
Opened 2020-10-29 10:04 UTC by DmitryKolinchuk

2020-11-04 17:50 UTC, ViacheslavAfanasyev requested changes

2020-11-04 17:50 UTC, ViacheslavAfanasyev commented on src/SIM.Tool.Windows/ButtonsConfiguration.cs
> +      this.settings = JObject.Parse(File.ReadAllText(Path.Combine(Directory.GetCurrentDirectory(),
Possible exception if there is no ButtonsConfiguration.json or just with the opening it?

2020-11-04 17:50 UTC, ViacheslavAfanasyev commented on src/SIM.Tool.Windows/CustomConverters/CustomGroupVisibilityConverter.cs
> +      Group = mainWindowGroup;
In some places you use this keyword, in others, you don't do it. Just follow the same code style across the whole solution.

2020-11-04 17:50 UTC, ViacheslavAfanasyev commented on src/SIM.Tool.Windows/CustomConverters/CustomGroupVisibilityConverter.cs
> +      throw new NotSupportedException();
Why we need a method which throws the exception?
If it isn't supported, maybe add it once it's supported?

2020-11-04 17:50 UTC, ViacheslavAfanasyev commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/AbstractInstanceButton.cs
> +        if (this.IsSitecoreMember(instance))
Maybe add enum with all possible types of the instance and simply check it instead of invoking methods?

2020-11-04 17:50 UTC, ViacheslavAfanasyev commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/AbstractInstanceButton.cs
> +    public virtual void OnClick([CanBeNull] Window mainWindow, Instance instance)
Empty method?

2020-11-04 17:50 UTC, ViacheslavAfanasyev commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/AbstractSimpleButton.cs
> +      return true;
Why we need methods which simply return true and don't do any logic? Why don't you make them abstract?

2020-11-04 17:50 UTC, ViacheslavAfanasyev commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/GenerateNuGetPackagesButton.cs
> +    {
Why do we need this ctor which does nothing

2020-11-04 17:50 UTC, ViacheslavAfanasyev commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/Install9InstanceButton.cs
> +          MainWindowHelper.SoftlyRefreshInstances();
Should be properly merged since my PR has changed in this file:
https://github.com/Sitecore/Sitecore-Instance-Manager/pull/468

2020-11-04 17:50 UTC, ViacheslavAfanasyev commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/OpenSimFolderButton.cs
> +      return true;
No logic always returns true

2020-11-04 17:50 UTC, ViacheslavAfanasyev commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/OpenSimFolderButton.cs
> +      return true;
No logic always returns true

2020-11-04 17:50 UTC, ViacheslavAfanasyev commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/OpenVisualStudioButton.cs
> +    {
Useless?

2020-11-04 18:12 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/CustomConverters/CustomGroupVisibilityConverter.cs
> +      Group = mainWindowGroup;
@ViacheslavAfanasyev what keyword do you mean?

2020-11-04 18:13 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/CustomConverters/CustomGroupVisibilityConverter.cs
> +      throw new NotSupportedException();
@ViacheslavAfanasyev, this code was written by ANP, so I left it as it is.

2020-11-04 18:14 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/AbstractInstanceButton.cs
> +        if (this.IsSitecoreMember(instance))
@ViacheslavAfanasyev, I am not sure that understand how this can be archived using enum.

2020-11-04 18:19 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/OpenSimFolderButton.cs
> +      return true;
@ViacheslavAfanasyev, yes it should be so, if needed the logic can be changed.

2020-11-04 18:19 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/OpenSimFolderButton.cs
> +      return true;
@ViacheslavAfanasyev, yes it should be so, if needed the logic can be changed.

2020-11-04 18:21 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/OpenVisualStudioButton.cs
> +    {
@ViacheslavAfanasyev, in this case, it should be empty, because only OnClick(Window mainWindow, Instance instance) is used.

2020-11-10 14:48 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/AbstractInstanceButton.cs
> +    public virtual void OnClick([CanBeNull] Window mainWindow, Instance instance)
@ViacheslavAfanasyev it is empty, because InstanceOnlyButton is abstract and its descendants should override this method to add needed logic.

2020-11-10 14:53 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/GenerateNuGetPackagesButton.cs
> +    {
@ViacheslavAfanasyev without it build fails with the following error:
**_'GenerateNuGetPackagesButton' does not contain a constructor that takes 1 arguments	SIM.Tool.Windows	C:\GitHub\Sitecore-Instance-Manager\src\SIM.Tool.Windows\MainWindowData.cs_**
However, as I can see the 'instance' parameter that is passed in the 'MainWindowData' class is not used for some reasons, so I will fix this.

2020-11-10 15:12 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/CustomConverters/CustomGroupVisibilityConverter.cs
> +      Group = mainWindowGroup;
key word 'this'

2020-11-10 15:17 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/AbstractInstanceButton.cs
> +        if (this.IsSitecoreMember(instance))
Convert methods to properties of instances.

2020-11-10 15:18 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/AbstractInstanceButton.cs
> +    public virtual void OnClick([CanBeNull] Window mainWindow, Instance instance)
Try to use abstract.

2020-11-10 15:21 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/GenerateNuGetPackagesButton.cs
> +    {
Delete GenerateNuGetPackagesButton.

2020-11-10 15:24 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/Install9InstanceButton.cs
> +          MainWindowHelper.SoftlyRefreshInstances();
Merge develop branch to avoid conflicts.

2020-11-10 15:39 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/AbstractSimpleButton.cs
> +      return true;
Discussed.

2020-11-12 08:01 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/ButtonsConfiguration.cs
> +      this.settings = JObject.Parse(File.ReadAllText(Path.Combine(Directory.GetCurrentDirectory(),
The same issue may occur in the "SIM.Sitecore9Installer.Configuration.Configuration" class.

2020-11-12 09:10 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/ButtonsConfiguration.cs
> +      this.settings = JObject.Parse(File.ReadAllText(Path.Combine(Directory.GetCurrentDirectory(),
@ViacheslavAfanasyev done.

2020-11-12 09:10 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/CustomConverters/CustomGroupVisibilityConverter.cs
> +      Group = mainWindowGroup;
@ViacheslavAfanasyev done.

2020-11-12 09:10 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/AbstractInstanceButton.cs
> +        if (this.IsSitecoreMember(instance))
@ViacheslavAfanasyev done.

2020-11-12 09:10 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/AbstractInstanceButton.cs
> +    public virtual void OnClick([CanBeNull] Window mainWindow, Instance instance)
@ViacheslavAfanasyev done.

2020-11-12 09:11 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/GenerateNuGetPackagesButton.cs
> +    {
@ViacheslavAfanasyev done.

2020-11-15 07:24 UTC, AndreyFilchenkov approved these changes

2020-11-15 15:45 UTC, ViacheslavAfanasyev approved these changes

2020-11-15 15:51 UTC, merged