#Add removing files directories if they exist
Sitecore/Sitecore-Instance-Manager pull request #554
Opened 2021-02-09 22:20 UTC by ViacheslavAfanasyev

“IndexWorker” subfolder of the “XConnect” folder should be removed by SIF task.
If some of the files are used, it doesn't remove the directory with the files.

We have a CleanUp processor which cleans empty folder.

I've added a condition if there are any files/folder in the root folder, it recursively removes all files(since Directory.Delete(target, true); doesn't remove files) and folders, so at this moment of time search indexer shouldn't use any files.

closes #549

2021-02-14 16:17 UTC, AndreyFilchenkov requested changes

2021-02-14 16:17 UTC, AndreyFilchenkov commented on src/SIM.Pipelines/Delete/CleanUp.cs
> +      }
It appears that the ```DeleteDirectoryWithFiles``` does the same as the:
```c#
Directory.Delete(param.Value, true);
```
does.

Could you clarify the purpose of introducing the method?

It appears to me that we need to fix the issue in the following way:
```c#
...
      if (param != null && Directory.GetFileSystemEntries(param.Value).Any())
      {
        Directory.Delete(param.Value, true);
      }
...
```

2021-02-24 21:38 UTC, ViacheslavAfanasyev commented on src/SIM.Pipelines/Delete/CleanUp.cs
> +      }
Agree. I've done it in the wrong way.
Fixed with adding a retry operation

2021-02-25 07:09 UTC, AndreyFilchenkov requested changes

2021-02-25 07:09 UTC, AndreyFilchenkov commented on src/SIM.Pipelines/Delete/CleanUp.cs
> +    async void RetryAction(Action action, int retrisNumber, int delayMs)
Could you please:
- avoid using the async code here. In any case, we need to wait until the cleanup operation is finished to see the results;
- in case the retry logic does not help to remove the folder, please consider throwing the exception. It will help to get notification about the problem;

2021-02-26 20:53 UTC, ViacheslavAfanasyev commented on src/SIM.Pipelines/Delete/CleanUp.cs
> +    async void RetryAction(Action action, int retrisNumber, int delayMs)
Done

2021-03-01 07:42 UTC, AndreyFilchenkov approved these changes

2021-03-01 08:02 UTC, DmitryKolinchuk approved these changes

2021-03-01 08:05 UTC, merged