#Add checking of JAVE_HOME variable
Sitecore/Sitecore-Instance-Manager pull request #555
Opened 2021-02-12 18:02 UTC by ViacheslavAfanasyev

Add simple checking of the variable:
https://www.screencast.com/t/y9wZcVRlOFE

Don't see a reason to introduce additional steps and write a validator since solr installation process won't have a big number or even more than one validator.

Closes #516

2021-02-14 16:32 UTC, AndreyFilchenkov requested changes

2021-02-14 16:32 UTC, AndreyFilchenkov commented on src/SIM.Tool.Windows/UserControls/Solr/SolrDetails.xaml.cs
> +      tasker.GlobalParams.First(p => p.Name == "JavaHome").Value = javaHomeVariable;
In case the ```JAVA_HOME``` variable is set, we need also the check if it contains a valid path to the existing Java.
For example, we can check the existence of the Java.exe file 
```{JAVA_HOME}```\bin\java.exe

2021-02-24 22:01 UTC, ViacheslavAfanasyev commented on src/SIM.Tool.Windows/UserControls/Solr/SolrDetails.xaml.cs
> +      tasker.GlobalParams.First(p => p.Name == "JavaHome").Value = javaHomeVariable;
Done

2021-02-26 19:45 UTC, ViacheslavAfanasyev commented
> The message seems to be not clear enough. Could you please update it.
> For example: "The 'JAVA_HOME' system variable does not point to the proper JRE folder." etc.

Done

2021-03-01 07:40 UTC, AndreyFilchenkov approved these changes

2021-03-01 07:50 UTC, DmitryKolinchuk approved these changes

2021-03-01 08:06 UTC, merged