Feature/557 sitecore 9 install packages
Sitecore/Sitecore-Instance-Manager pull request #570
Opened 2021-03-19 12:02 UTC by DmitryKolinchuk

2021-03-24 15:28 UTC, ViacheslavAfanasyev requested changes

2021-03-24 15:28 UTC, ViacheslavAfanasyev commented on src/SIM.Base/WebRequestHelper.cs
>    using System.Threading;
The followings are not related to particular code:

Unable to get authentication cookie even the password default:
https://www.screencast.com/t/Or5kLSzVr

Freeze if Sitecore instance(or Identity) isnt' run:
https://www.screencast.com/t/v9gj3ueuBGN

2021-04-13 12:26 UTC, DmitryKolinchuk commented on src/SIM.Base/WebRequestHelper.cs
>    using System.Threading;
@ViacheslavAfanasyev the first issue occurs because Sitecore site of XP0 topology doesn't have 'https' binding, by default it is 'http' after installation.
The SSC Auth services that are needed for package installation require an SSL/TLS connection, so a valid certificate and SSL binding for the Sitecore site are needed to be set up.
After discussion with @AndreyFilchenkov, we decided to add validators for this and other cases based on the HTTP status code that is returned after accessing a Sitecore instance to get authentication cookie.  
I also registered the [separate issue](https://github.com/Sitecore/Sitecore-Instance-Manager/issues/579) to investigate if it is possible to change this behavior on the SIM side in order to have SSL bindings for all Sitecore sites after installation

The second issue is also covered by the validator and freezing is fixed by using long running task when a request to the Sitecore sire or Sitecore Identity Server is executed.

Please review the changes and let me know if you have additional remarks.

2021-04-15 15:42 UTC, ViacheslavAfanasyev requested changes

2021-04-15 15:42 UTC, ViacheslavAfanasyev commented on src/SIM.Base/WebRequestHelper.cs
>    using Sitecore.Diagnostics.Base;
It uses a different hostname from the default one and this hostname is not configured on the Identity Server to login.
https://www.screencast.com/t/HeqJU1YtC9z

It's just 9.0 where Identity Server is installed with commerce.

2021-04-15 15:42 UTC, ViacheslavAfanasyev commented on src/SIM.Base/WebRequestHelper.cs
>    using Sitecore.Diagnostics.Logging;
Not clear(maybe I've missed during the meeting) why an instance which has not HTTPS binding can not install the package, while SIM is able to login:
https://www.screencast.com/t/LuhEKNl6

2021-04-16 06:45 UTC, DmitryKolinchuk commented on src/SIM.Base/WebRequestHelper.cs
>    using Sitecore.Diagnostics.Logging;
@ViacheslavAfanasyev yes, we discussed this during the meeting. I also provided the explanation in my previous reply:

> The SSC Auth services that are needed for package installation require an SSL/TLS connection, so a valid certificate and SSL binding for the Sitecore site are needed to be set up.
> After discussion with @AndreyFilchenkov, we decided to add validators for this and other cases based on the HTTP status code that is returned after accessing a Sitecore instance to get authentication cookie.
> I also registered the separate issue to investigate if it is possible to change this behavior on the SIM side in order to have SSL bindings for all Sitecore sites after installation

2021-04-22 17:27 UTC, IvanSheyenko approved these changes

2021-04-22 17:27 UTC, IvanSheyenko commented on src/SIM.Pipelines/Agent/AgentFiles.cs
> +      Sitecore.Context.SetActiveSite(""shell"");
consider using switcher

2021-06-03 07:45 UTC, DmitryKolinchuk commented on src/SIM.Base/WebRequestHelper.cs
>    using Sitecore.Diagnostics.Base;
@ViacheslavAfanasyev the logic of resolving hostnames takes the first one that has SSL from IIS site's bindings. Installing a package on Sitecore 9.0 requires the hostname with the valid certificate defined in the IIS bindings for your site (this was already discussed). However, it appeared that Commerce adds the described SSL hostname without a valid certificate, please see the following screenshot:
[https://www.screencast.com/t/rtfSypI5](https://www.screencast.com/t/rtfSypI5)
That is why the error occurs and to resolve it a user should make sure that a valid certificate is used for the SSL binding of the Sitecore site as stated in the message.
This is by design implementation and it was discussed with @AndreyFilchenkov.

2021-06-03 08:28 UTC, AndreyFilchenkov approved these changes

2021-06-04 12:56 UTC, ViacheslavAfanasyev approved these changes

2021-06-04 12:59 UTC, merged