#Cannot uninstall Sitecore if the wdp package was deleted
Sitecore/Sitecore-Instance-Manager pull request #585
Opened 2021-04-26 20:02 UTC by ViacheslavAfanasyev

closes #506

2021-05-02 07:47 UTC, AndreyFilchenkov requested changes

2021-05-02 07:47 UTC, AndreyFilchenkov commented on src/SIM.Sitecore9Installer/Tasker.cs
> +          if (!string.IsNullOrEmpty(taskFile))
Could you please remove extra tab/spaces?

2021-05-02 07:47 UTC, AndreyFilchenkov commented on src/SIM.Sitecore9Installer/Tasker.cs
> +            }
Could you please remove extra tab/spaces?

2021-05-05 13:00 UTC, ViacheslavAfanasyev commented on src/SIM.Sitecore9Installer/Tasker.cs
> +          if (!string.IsNullOrEmpty(taskFile))
I haven't got which ones? Could you please clarify what you mean? :-)

2021-05-06 16:42 UTC, ViacheslavAfanasyev commented on src/SIM.Sitecore9Installer/Tasker.cs
> +          if (!string.IsNullOrEmpty(taskFile))
I've tried to fix but it seems doesn't work ;-)

2021-05-19 13:27 UTC, IvanSheyenko approved these changes

2021-05-19 13:28 UTC, merged