Feature/595 outdated link to web platform download installer in prerequisites.json file
Sitecore/Sitecore-Instance-Manager pull request #603
Opened 2021-07-28 06:23 UTC by DmitryKolinchuk

2021-08-25 07:11 UTC, AndreyFilchenkov approved these changes

2021-08-31 14:51 UTC, ViacheslavAfanasyev requested changes

2021-08-31 14:51 UTC, ViacheslavAfanasyev commented on src/SIM.Sitecore9Installer/Validation/Validators/PrerequisitesDownloadLinksValidator.cs
> +          var response = authClient.SendAsync(new HttpRequestMessage(HttpMethod.Head, new Uri(link))).Result;
In case a user install an instance in airplane mode(turned off network), the user gets the warnings that don't induce action. What to do, etc.
As far as I got the intent of this PR was to fix outdated links.

2021-09-01 06:38 UTC, DmitryKolinchuk commented on src/SIM.Sitecore9Installer/Validation/Validators/PrerequisitesDownloadLinksValidator.cs
> +          var response = authClient.SendAsync(new HttpRequestMessage(HttpMethod.Head, new Uri(link))).Result;
@ViacheslavAfanasyev

> In case a user install an instance in airplane mode(turned off network), the user gets the warnings that don't induce action. 

In this case, the following warnings appear:
![image](https://user-images.githubusercontent.com/20965100/131622601-f0a4a4f2-372f-48b7-acf3-0fe0b7477b77.png)
They state that links are not accessible.
However, I agree that we can extend the existing message as follows:

_**Please check the Internet connection and the link accessibility in a browser.
This behavior may also occur due to similar symptoms described in the following known issue:
https://github.com/Sitecore/Sitecore-Instance-Manager/wiki/Known-Issue-Outdated-Download-Link-to-Microsoft-Web-Platform-Installer**_

@AndreyFilchenkov, what do think?

> As far as I got the intent of this PR was to fix outdated links.

This was discussed with @AndreyFilchenkov that it is better to introduce validator of all links instead of fixing the known corrupted link because some other links can be not available in future.

2021-09-01 14:08 UTC, AndreyFilchenkov commented on src/SIM.Sitecore9Installer/Validation/Validators/PrerequisitesDownloadLinksValidator.cs
> +          var response = authClient.SendAsync(new HttpRequestMessage(HttpMethod.Head, new Uri(link))).Result;
I agree with adding the additional clarification message, that will help to understand how to fix the issue.

2021-09-03 05:25 UTC, DmitryKolinchuk commented on src/SIM.Sitecore9Installer/Validation/Validators/PrerequisitesDownloadLinksValidator.cs
> +          var response = authClient.SendAsync(new HttpRequestMessage(HttpMethod.Head, new Uri(link))).Result;
@ViacheslavAfanasyev, @AndreyFilchenkov please check the latest update.

2021-09-16 13:10 UTC, ViacheslavAfanasyev approved these changes

2021-09-16 13:43 UTC, merged