Feature/610 analyze log files and open log file commands in context menu do not work for sitecore members
Sitecore/Sitecore-Instance-Manager pull request #612
Opened 2021-09-03 13:58 UTC by DmitryKolinchuk

2021-09-16 13:32 UTC, ViacheslavAfanasyev requested changes

2021-09-16 13:32 UTC, ViacheslavAfanasyev commented on src/SIM.Instances/Instance.cs
>        try
I don't have an exact line when the following happens but I've noticed 2 issues:

Freeze after clicking "Open log file"
Can not close the window with logs
See screencast showing both issues: https://www.screencast.com/t/8I89XhDr
If it's not related to the current PR, just need to create a separate issue

2021-09-16 13:40 UTC, DmitryKolinchuk commented on src/SIM.Instances/Instance.cs
>        try
@ViacheslavAfanasyev, these issues are reproduced in the latest SIM release without PR changes.
Please refer to the following screencast:
https://www.screencast.com/t/4a3SP6eVRS
Could you please create separate issues for these scenarios?
**CC:** @AndreyFilchenkov

2021-09-16 14:04 UTC, AndreyFilchenkov requested changes

2021-09-16 14:04 UTC, AndreyFilchenkov commented on src/SIM.Tool.Windows/LogFileFolder/SitecoreMembersLogFileFolderResolver.cs
> +      return new SitecoreDefaultLogFileFolderResolver(_instance).GetLogFolder();
It would be better not to reference one resolver from another. Please consider moving the "fallback" logic to OpenLogsButton.cs type.

2021-09-16 14:04 UTC, AndreyFilchenkov commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/OpenLogsButton.cs
potentially the fallback logic can be implemented in the following way:
``` c#
string logs = LogFileFolderFactory.GetResolver(instance).GetLogFolder() ?? LogFileFolderFactory.GetDefaultResolver(instance);
```

2021-09-16 14:22 UTC, ViacheslavAfanasyev approved these changes

2021-09-17 06:20 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/LogFileFolder/SitecoreMembersLogFileFolderResolver.cs
> +      return new SitecoreDefaultLogFileFolderResolver(_instance).GetLogFolder();
@AndreyFilchenkov, this has been fixed.

2021-09-17 06:20 UTC, DmitryKolinchuk commented on src/SIM.Tool.Windows/MainWindowComponents/Buttons/OpenLogsButton.cs
Done.

2021-09-17 06:44 UTC, AndreyFilchenkov approved these changes

2021-09-17 06:44 UTC, merged